```mermaid
graph TD
    Start[Start] --> GitStatus{Check Git Status}
    GitStatus -->|No Changes| Exit0[Exit Program]
    GitStatus -->|Changes Detected| StageAllChanges[Stage All Changes]
    StageAllChanges --> ParseGitStatusOutput[Parse Git Status Output]
    ParseGitStatusOutput --> MakeManifestModifiedSources[Make Manifest from Modified Sources]
    ParseGitStatusOutput --> RestoreDeletedFiles

    MakeManifestModifiedSources --> ConvertModifiedSourcesXML[Convert Modified Sources to XML]
    ConvertModifiedSourcesXML --> MoveConstructiveDeploy[Move package.xml to Constructive Deploy Directory]
    MoveConstructiveDeploy --> Exit0

    RestoreDeletedFiles[Restore Deleted Files] --> MakeManifestDeletedSources
    MakeManifestDeletedSources --> ConvertDeletedSourcesXML[Convert Deleted Sources to XML]
    ConvertDeletedSourcesXML --> MoveDestructiveChanges[Move package.xml to Destructive Changes Directory]
    MoveDestructiveChanges --> DeleteRestoredFiles[Delete Restored Files]
    DeleteRestoredFiles --> Exit0
```